### ISSUE TITLE
Anonimatron fails silently if there are two DBs with the same table

### ISSUE THREAD

**Issue by jonyt** [realrolfje/anonimatron#106]
If there are two DBs containing a table with the same name then the process will silently fail. Partly this is because the primary keys for both tables will be retrieved by [this](https://github.com/realrolfje/anonimatron/blob/17d92653c7070213c59a5908c32a24e63aecb859/src/main/java/com/rolfje/anonimatron/jdbc/JdbcAnonymizerService.java#L366) line in case the user has access to both DBs. 

One possible fix would be to narrow the scope of the search by passing the catalog name to [getPrimaryKeys](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getPrimaryKeys(java.lang.String,%20java.lang.String,%20java.lang.String)).  However, this is only a partial fix. I still need to find out why the process leaves the table untouched in this case.

**Comment by realrolfje** [comment]
This is related to #105 where de search scope was not narrowed to the current catalog.

Leaving the table untouched could be caused by anonimatron getting the primary keys for db1.table, but tries to process db2.table with that information. I have not tested this (yet)
