### ISSUE TITLE
error when trying to use RANDOMCHARACTERS 

### ISSUE THREAD

**Issue by baronnenate** [realrolfje/anonimatron#127]
I am trying to run a test using the RANDOMCHARACTERS, but am receiving an error:
Please provide 'characters' as configuration parameter.

I can't see from the documentation where or how I am supposed to provide this parameter, can you advise? 

cheers.

**Comment by baronnenate** [comment]
ignore...  I spotted it in the sample xml config

**Comment by realrolfje** [comment]
No problem :-)
