### ISSUE TITLE
After successfully anonymized db, want to wrote back my original database.

### ISSUE THREAD

**Issue by arielpriya** [realrolfje/anonimatron#174]
Hi, 

Currently I am using this tool for my project.

I have anonymizes my database successfully, Now I want wrote back my original database. is there any possible solution?

As document mentioned "The private data “moved” from the database into the synonyms.xml file we created. So that becomes the new data to watch. Store it in a safe place where nobody can access it", so can I wrote back my original db using synonyms.xml file.
If yes then how?

**Comment by realrolfje** [comment]
Hello Ariel,

Thanks for using Anonimatron! To answer your question: No, Anonimatron cannot restore the original data from your synonyms file. The synonyms file is not a "backup" of your original database. Anonimatron is designed to run on a copy of your original database. Maybe this is not clear in the documentation.

The typical way to use anonimatron is to copy the production database or restore a backup in a separate location, then run anonimatron on that copy, and give that copy to developers. There is no "way back".

I hope this helps, cheers,
Rolf

**Comment by arielpriya** [comment]
Thanks for the response @realrolfje.
