### ISSUE TITLE
Request for new Relase

### ISSUE THREAD

**Issue by ubeth** [realrolfje/anonimatron#233]
It would be nice if there could be an new release including the pull request #151, which was merged on Jan 29, 2022 and which we are waiting for.

**Comment by realrolfje** [comment]
You are totally right Ubeth, I'll see what I can do, hang in there

**Comment by realrolfje** [comment]
The only thing missing is the release to maven central, I need to figure out how to renew my gpg key there but the zip file of v1.16 is online now, I hope this helps. Cheers!

**Comment by realrolfje** [comment]
Maven repo upload also done, all sorted!
