### ISSUE TITLE
Support anonymising IBAN values

### ISSUE THREAD

**Issue by fbascheper** [realrolfje/anonimatron#28]
Currently only Dutch bank accounts are supported for anonymisation.
It would be great if IBAN generation would also be supported within Anonimatron.

**Comment by realrolfje** [comment]
I was also thinking of adding a configurable bank code, so anonymized IBANS woulnd have a "RND" code or something alike. For applications which do not validate the bank codes this could be an extra safety to never ever have an existing bank account, while the format is technically still ok to parse.
