### ISSUE TITLE
Getting Invalid or Corrupted jar file error

### ISSUE THREAD

**Issue by neobe87** [realrolfje/anonimatron#3]
Hi,

I'm trying to use your tool - but if I try to run it I get the above error message.
I recommend the issue is in classes12-0.0.jar.
I'm using a fresh copy of anonimatron-v1.8.2.
Also tryed v1.8.1 with no luck

Thanks for your help.

**Comment by realrolfje** [comment]
Hi, I know it's a "bit late", but are you still having this problem?
