### ISSUE TITLE
Error running anonimatron script on mac

### ISSUE THREAD

**Issue by neelp1** [realrolfje/anonimatron#42]
Anonimatron version:
Operating system and version:
Java runtime (`java -version`):
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

#### Executed commands or actions:
/anonimatron.sh

#### Expected outcome or behavior:
This is Anonimatron 1.7, a command line tool to consistently
replace live data in your database with data data which
can not be traced back to the original data.
You can use this tool to transform a dump from a production
database into a large representative dataset you can
share with your development and test team.
Use the -configexample command line option to get an idea of
what your configuration file needs to look like.
 
usage: java -jar anonimatron.jar
 -config      The XML Configuration file describing what to
                   anonymize.
 -configexample    Prints out a demo/template configuration file.
 -dryrun           Do not make changes to the database.
 -synonyms    The XML file to read/write synonyms to. If the file
                   does not exist it will be created.

#### Actual outcome or behavior:
Error: Could not find or load main class com.rolfje.anonimatron.Anonimatron
/Users/myusername/myfolder/realrolfje-anonimatron-31e1800/resources/scripts

**Comment by Egahras** [comment]
Same here

**Comment by realrolfje** [comment]
Related to #44

**Comment by realrolfje** [comment]
Solved in #44
