### ISSUE TITLE
Could not find or load main class com.rolfje.anonimatron.Anonimatron

### ISSUE THREAD

**Issue by Egahras** [realrolfje/anonimatron#44]
Anonimatron version:
Operating system and version:
Java runtime (`java -version`):
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

#### Executed commands or actions:
scripts/ anonimatron.sh

#### Expected outcome or behavior:
Running anonimatron as described in readme

#### Actual outcome or behavior:
Error: Could not find or load main class com.rolfje.anonimatron.Anonimatron
Caused by: java.lang.ClassNotFoundException: com.rolfje.anonimatron.Anonimatron
/test/realrolfje-anonimatron-31e1800/resources/scripts

1. Started a fresh docker container with ubuntu:latest. 
2. Installed mysql-server and default-jdk. 
3. Downloaded zip and extracted in /test
4. running /test/realrolfje-anonimatron-31e1800/resources/scripts/anonimatron.sh

**Comment by Moinlil** [comment]
Having the same problem in windows, can anyone help?

How do we fix this->

Error: Could not find or load main class com.rolfje.anonimatron.Anonimatron
Caused by: java.lang.ClassNotFoundException: com.rolfje.anonimatron.Anonimatron
/test/realrolfje-anonimatron-31e1800/resources/scripts

**Comment by realrolfje** [comment]
For MacOS and Linux this appeared to be a problem in anonimatron.sh where the directory of the script did not resolve correctly.
