### ISSUE TITLE
Support anonymizer parameters for columns

### ISSUE THREAD

**Issue by Pyeroh** [realrolfje/anonimatron#54]
It's a suggestion, but also a way to specify this feature.

With the configuration file, it should be possible to pass parameters to a custom anonymizer. These parameters : 
- are to be placed on a `column` node, 
- interpreted as a Map in the Column class,
- if the anonymizer supports parameters (with an interface inherited from Anonymizer), it is called with the parameters.

I'm currently working on it, what do you think of it ?

**Comment by realrolfje** [comment]
Merged into develop, part of next release
