### ISSUE TITLE
Build fails due to missing codehaus repository

### ISSUE THREAD

**Issue by sushiomsky** [realrolfje/anonimatron#9]
Anonimatron version:
Operating system and version: Linux, Win10
Java runtime (`java -version`): 1.8
Hi I tried to build Anonimatron with Maven in Eclipse and IntelliJ. Maven can't resolve the dependencies as it tries to get the from http://repository.codehaus.org but codehaus is down...
Do you have any quick solution for this problem?
Thanks in advance

**Comment by realrolfje** [comment]
Solved.
